### ISSUE TITLE
Trying to get this working on Laravel 5.4

### ISSUE THREAD

**Issue by nmfarshad** [sixty-nine/php-cloud-lib#11]
Installed using composer and added the dependencies 
```
use SixtyNine\Cloud\Builder\WordsListBuilder;
use SixtyNine\Cloud\Builder\CloudBuilder;
use SixtyNine\Cloud\Builder\FiltersBuilder;
```
A simple list builder code isnt working for me what am I missing ?

`		$list = WordsListBuilder::importWords('foobar foo foo bar')
    			->build('foobar');`

ERROR

```
syntax error, unexpected '?'
--
in ArrayCollection.php (line 240)


```

**Comment by sixty-nine** [comment]
Could you please provide the stack trace of the error?

Also, does the error show if you don't chain the build() method (i.e. only with importWords)?

**Comment by sixty-nine** [comment]
Please re-open with more info
