### ISSUE TITLE
ErrorException: Division by zero

### ISSUE THREAD

**Issue by AidasK** [sixty-nine/php-cloud-lib#14]
ErrorException: Division by zero
#63 vendor/sixty-nine/php-cloud-lib/src/SixtyNine/Cloud/FontSize/DimFontSizeGenerator.php(17): handleError
#62 vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): handleError
#61 vendor/sixty-nine/php-cloud-lib/src/SixtyNine/Cloud/FontSize/DimFontSizeGenerator.php(17): calculateFontSize
#60 vendor/sixty-nine/php-cloud-lib/src/SixtyNine/Cloud/Builder/CloudBuilder.php(204): addWords
#59 vendor/sixty-nine/php-cloud-lib/src/SixtyNine/Cloud/Builder/CloudBuilder.php(177): build

I might have given a strange input for this function, but it should check for zero division.

**Comment by sixty-nine** [comment]
I quickly checked the code. the division by zero is caused by $maxCount being zero in the following line:

```
return (int)($minFontSize + $deltaFont * pow($count / $maxCount, 2));
```
Following the code it looks like WordList::getWordsMaxCount() is returning zero.

That does not really make sense, it means your word list contains only words with a "count" of zero, i.e. never used.

The better fix I can see is to simply fail (raise an InvalidArgumentException) if in CloudBuilder::addWords(), $maxCount is zero.

Unfortunately I don't have time to address this right now. Either be patient, or use the above hints to create a PR.

**Comment by sixty-nine** [comment]
Insert this in CloudBuilder at line 201...
```
if (!$word->getCount()) {
  continue;
}
```
And write a test :)

**Comment by sixty-nine** [comment]
Hello, I have been trying to write a test to reproduce this error but could not get anything failing.

Here is what I tried:

```
    public function testEmptyListShouldNotFail()
    {
        $list = WordsListBuilder::create()->setMaxWords(0)->build('foobar');
        $factory = FontsFactory::create(__DIR__.'/../fixtures/fonts');
        $cloud = CloudBuilder::create($factory)
            ->setFont('Arial.ttf')
            ->useList($list)
            ->build()
        ;
    }
```
Could you give more details on the "strange input" that caused the division by zero?

**Comment by AidasK** [comment]
I was able to reproduce this with this line:
```
        $list->addWord((new Word())->setCount(0)->setText('1'));
```
I have added a word with count 0 which created a zero division. 
My use case was to generate a cloud of my best friends. Each friend had a score and some of them had a score 0. To fix this I am now using $score + 1. 

In the library this can be fixed by doing `max($maxCount, 1)` or by not allowing to set count to 0 (Invalid param exception).

**Comment by sixty-nine** [comment]
Merci.

It's corrected. I choosed the fix I proposed above: if a word is not used (count = 0) then do not use it in the cloud. I think it's the best for most use cases. In your particular case, if it is important to display friends with score 0 in the cloud, I suggest the business remains on your part just like you are doing now by adding 1 to the score.

I'm happy to see this code I wrote for fun is actually used out there :)

**Comment by AidasK** [comment]
I know that feeling, it is actually used here: http://catfly.com/play/which-names-are-most-important-in-your-life/ Enjoy! :)

It's a pity that PHP has such a bad image manipulation library, so implementing something like https://github.com/zverok/magic_cloud might be impossible or very slow.

**Comment by sixty-nine** [comment]
I quickly checked the code of magic_cloud, and basically they are doing the same as here: follow a spiral starting from the center to look for a place. Nothing in php-cloud-lib would prevent to rotate words. Attention must be paid with the collision check since it's quite more complicated (I mean performance-wise) to do with non-axis-aligned rectangles, but that's it...

**Comment by AidasK** [comment]
Also php-cloud-lib uses imagettfbbox which is highly inaccurate and there is no alternative to it. 
<img width="156" alt="screen shot 2018-06-08 at 10 03 44" src="https://user-images.githubusercontent.com/2088484/41143994-0327441a-6b04-11e8-9c7c-f9f5897f2654.png">
This image shows that they are not probably using boxes because some words fits in the round areas. Though I haven't tried ruby lib and it might be super slow, not sure. To me, this lib would have no use if it would be slow, performance is the key for me.

**Comment by sixty-nine** [comment]
Yes that's interesting..

I am not very used to follow Ruby code on github and don't know the ecosystem, but what I understand is that they are drawing the text in a canvas, then read it pixel by pixel to extract the exact mask of the drawn word. 

It's Friday night, I'm even too lazy to check, but there is for sure a function to read an image pixel by pixel in php. So yeah, it's quite some work, but it feasible :)

Now to be honest I'd be more inclined to rewrite this whole stuff in JS than extending this lib much further ;)
